In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size=10000

In [24]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1045, 3701, 5528, 1481],
 [1045, 3701, 5528, 8859],
 [1045, 6635, 5528, 8686],
 [5472, 262, 7378, 5144, 1488],
 [5472, 262, 7378, 5144, 3241],
 [8597, 1045, 3276, 5528, 9233],
 [2937, 3216, 6423, 5144]]

In [25]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

from tensorflow.keras.utils import pad_sequences

from tensorflow.keras.models import Sequential

In [26]:
import numpy as np

In [27]:
sent_length = 8         # Maximum possible length of any Sentence ( Let's take 8)

embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 1045 3701 5528 1481]
 [   0    0    0    0 1045 3701 5528 8859]
 [   0    0    0    0 1045 6635 5528 8686]
 [   0    0    0 5472  262 7378 5144 1488]
 [   0    0    0 5472  262 7378 5144 3241]
 [   0    0    0 8597 1045 3276 5528 9233]
 [   0    0    0    0 2937 3216 6423 5144]]


In [28]:
## feature representation
dim=10

In [29]:
import tensorflow as tf

model=Sequential()

model.add(tf.keras.Input(shape=(sent_length,)))

model.add(Embedding(voc_size, dim, mask_zero=True))    
#You're not passing data, Giving the structure to the model — telling it what kind of data to expect and how to process it.


## Output Shape---(8, 10) → 8 words each converted into 10-d embeddings


In [30]:
model.compile(optimizer='adam', loss='mse')    ## Optimizer and Loss Function

In [31]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs) 
# It will return the model’s output predictions for each input sample in embedded_docs

# Each word index is mapped to a 10 D vector

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step


array([[[-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.01875897,  0.002499  ,  0.03734622,  0.00475975,
         -0.02478262,  0.04509974, -0.02682613, -0.00801697,
         -0.02880763,  0.04109843],
        [-0.03988868,  0.02266217,  0.01228905,  0.0279125 ,
          0.02682679, -0.03129778,  0.00856391, -0.0422442 ,
         -0.04081836, -0.02780765],
        [ 0.04100898,  0.01130603,  0.01620242,  0.0

In [33]:
embedded_docs[0]

array([   0,    0,    0,    0, 1045, 3701, 5528, 1481], dtype=int32)

In [34]:
model.predict(np.array([embedded_docs[0]]))


# 8 words each of dimension-10

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step


array([[[-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.0147207 ,  0.00742968, -0.04264187, -0.0001526 ,
          0.03440214,  0.02763033,  0.00322058, -0.01889924,
          0.04349754, -0.04671399],
        [-0.01875897,  0.002499  ,  0.03734622,  0.00475975,
         -0.02478262,  0.04509974, -0.02682613, -0.00801697,
         -0.02880763,  0.04109843],
        [-0.03988868,  0.02266217,  0.01228905,  0.0279125 ,
          0.02682679, -0.03129778,  0.00856391, -0.0422442 ,
         -0.04081836, -0.02780765],
        [ 0.04100898,  0.01130603,  0.01620242,  0.0

In [35]:
embedded_docs[0].shape        # (8,)

(8,)

In [36]:

np.array([embedded_docs[0]]).shape  # (1, 8) ✅ valid for Keras


(1, 8)